services:
  db:
    container_name: ${POSTGRES_CONTAINER_NAME}
    build:
      context: psql
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
        PGDATA: ${PGDATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./psql/pgdata:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge